# Generated by Django 3.0.5 on 2020-05-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_delete_order'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='OrderProduct',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='prtoducts',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='item',
            new_name='product',
        ),
    ]
