# Generated by Django 3.0.5 on 2020-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Product name', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10000)),
                ('description', models.TextField(default='Product description')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
