# Generated by Django 3.0.5 on 2020-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('O', 'Inne'), ('M', 'Męskie'), ('W', 'Damskie'), ('K', 'Dziecięce')], default='O', max_length=1),
        ),
    ]
