# Generated by Django 3.0.5 on 2020-04-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('o', 'Inne'), ('m', 'Męskie'), ('w', 'Damskie'), ('k', 'Dziecięce')], default='o', max_length=1),
        ),
    ]
