# Generated by Django 3.0.5 on 2020-05-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
