# Generated by Django 3.0.5 on 2020-05-01 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_orderproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prtoducts',
            new_name='products',
        ),
    ]
