# Generated by Django 3.0.5 on 2020-05-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200501_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Adres', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Miasto', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='Imię', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Nazwisko', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(default='Płatność', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default='Kod pocztowy', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.TextField(default='Product short description (means product code)'),
        ),
    ]
